'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

#If Silverlight Then
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
System.Runtime.Serialization.DataContractAttribute(Name:="IndividualOptions", [Namespace]:="http://schemas.datacontract.org/2004/07/Sonda.BPM.Model",[IsReference]:=True)>  _
Partial Public Class IndividualOptions
#Else
<Serializable()>  _
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
System.Runtime.Serialization.DataContractAttribute(Name:="IndividualOptions", [Namespace]:="http://schemas.datacontract.org/2004/07/Sonda.BPM.Model",[IsReference]:=True)>  _
Partial Public Class IndividualOptions
#End If
Implements System.ComponentModel.INotifyPropertyChanged
    #Region "Primitive Properties"
	Private _id As Long

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Id As Long
        Get
            Return _id
        End Get
        Set(ByVal value As Long)
			If (Object.ReferenceEquals(Me._id, value) <> True) Then
				_id = value
				Me.RaisePropertyChanged("Id")
            End If
		End Set
	End Property
	Private _original_Id As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Original_Id As String
        Get
            Return _original_Id
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._original_Id, value) <> True) Then
				_original_Id = value
				Me.RaisePropertyChanged("Original_Id")
            End If
		End Set
	End Property
	Private _date As Nullable(Of Date)

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property [Date] As Nullable(Of Date)
        Get
            Return _date
        End Get
        Set(ByVal value As Nullable(Of Date))
			If (Object.ReferenceEquals(Me._date, value) <> True) Then
				_date = value
				Me.RaisePropertyChanged("[Date]")
            End If
		End Set
	End Property
	Private _type As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Type As String
        Get
            Return _type
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._type, value) <> True) Then
				_type = value
				Me.RaisePropertyChanged("Type")
            End If
		End Set
	End Property
	Private _description As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Description As String
        Get
            Return _description
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._description, value) <> True) Then
				_description = value
				Me.RaisePropertyChanged("Description")
            End If
		End Set
	End Property

    #End Region


    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub

End Class
