'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.EntityClient

Partial Public Class ModelContainer
    Inherits ObjectContext
    Public Const SettingsConnectionString As String = "name=ModelContainer"
    Public Const ContainerName As String = "ModelContainer"

#Region "Constructors"

    Public Sub New()
        MyBase.New(SettingsConnectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

#End Region
#Region "ObjectSet Properties"

    Public ReadOnly Property Events() As ObjectSet(Of [Event])
        Get
            If _events Is Nothing Then
                _events = CreateObjectSet(Of [Event])("Events")
            End If
            Return _events
        End Get
    End Property
    Private _events As ObjectSet(Of [Event])

    Public ReadOnly Property Families() As ObjectSet(Of Family)
        Get
            If _families Is Nothing Then
                _families = CreateObjectSet(Of Family)("Families")
            End If
            Return _families
        End Get
    End Property
    Private _families As ObjectSet(Of Family)

    Public ReadOnly Property Individuals() As ObjectSet(Of Individual)
        Get
            If _individuals Is Nothing Then
                _individuals = CreateObjectSet(Of Individual)("Individuals")
            End If
            Return _individuals
        End Get
    End Property
    Private _individuals As ObjectSet(Of Individual)

    Public ReadOnly Property Media() As ObjectSet(Of Media)
        Get
            If _media Is Nothing Then
                _media = CreateObjectSet(Of Media)("Media")
            End If
            Return _media
        End Get
    End Property
    Private _media As ObjectSet(Of Media)

#End Region
End Class
