'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

#If Silverlight Then
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
System.Runtime.Serialization.DataContractAttribute(Name:="Request", [Namespace]:="http://schemas.datacontract.org/2004/07/Sonda.BPM.Model",[IsReference]:=True)>  _
Partial Public Class Request
#Else
<Serializable()>  _
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
System.Runtime.Serialization.DataContractAttribute(Name:="Request", [Namespace]:="http://schemas.datacontract.org/2004/07/Sonda.BPM.Model",[IsReference]:=True)>  _
Partial Public Class Request
#End If
Implements System.ComponentModel.INotifyPropertyChanged
    #Region "Primitive Properties"
	Private _id As Long

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Id As Long
        Get
            Return _id
        End Get
        Set(ByVal value As Long)
			If (Object.ReferenceEquals(Me._id, value) <> True) Then
				_id = value
				Me.RaisePropertyChanged("Id")
            End If
		End Set
	End Property
	Private _email As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Email As String
        Get
            Return _email
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._email, value) <> True) Then
				_email = value
				Me.RaisePropertyChanged("Email")
            End If
		End Set
	End Property
	Private _name As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Name As String
        Get
            Return _name
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._name, value) <> True) Then
				_name = value
				Me.RaisePropertyChanged("Name")
            End If
		End Set
	End Property
	Private _phone As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Phone As String
        Get
            Return _phone
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._phone, value) <> True) Then
				_phone = value
				Me.RaisePropertyChanged("Phone")
            End If
		End Set
	End Property
	Private _text As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Text As String
        Get
            Return _text
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._text, value) <> True) Then
				_text = value
				Me.RaisePropertyChanged("Text")
            End If
		End Set
	End Property
	Private _original_Id As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Original_Id As String
        Get
            Return _original_Id
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._original_Id, value) <> True) Then
				_original_Id = value
				Me.RaisePropertyChanged("Original_Id")
            End If
		End Set
	End Property
	Private _date As Date

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property [Date] As Date
        Get
            Return _date
        End Get
        Set(ByVal value As Date)
			If (Object.ReferenceEquals(Me._date, value) <> True) Then
				_date = value
				Me.RaisePropertyChanged("[Date]")
            End If
		End Set
	End Property
	Private _iP As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property IP As String
        Get
            Return _iP
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._iP, value) <> True) Then
				_iP = value
				Me.RaisePropertyChanged("IP")
            End If
		End Set
	End Property
	Private _reason As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Reason As String
        Get
            Return _reason
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._reason, value) <> True) Then
				_reason = value
				Me.RaisePropertyChanged("Reason")
            End If
		End Set
	End Property
	Private _attachmentsQty As Integer

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property AttachmentsQty As Integer
        Get
            Return _attachmentsQty
        End Get
        Set(ByVal value As Integer)
			If (Object.ReferenceEquals(Me._attachmentsQty, value) <> True) Then
				_attachmentsQty = value
				Me.RaisePropertyChanged("AttachmentsQty")
            End If
		End Set
	End Property
	Private _attachments As String

	<System.Runtime.Serialization.DataMemberAttribute()> _
Public Overridable Property Attachments As String
        Get
            Return _attachments
        End Get
        Set(ByVal value As String)
			If (Object.ReferenceEquals(Me._attachments, value) <> True) Then
				_attachments = value
				Me.RaisePropertyChanged("Attachments")
            End If
		End Set
	End Property

    #End Region


    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged

    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub

End Class
